[build-system]
requires = ["poetry-core>=1.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "mock-project"
version = "0.1.0"
packages = [{ include = "my_project", from = "src" }]

[tool.poetry.requires-plugins]
someplugin = "value"

[dependency-groups]
dev = ["pytest>=9.0"]

[project.scripts]
transition-to-uv = "scripts.transition_to_uv:main"
other-script = "my_project.main:main"
